### ISSUE TITLE
[binding-http] Observable properties result in error

### ISSUE THREAD

**Issue by egekorkan** [eclipse/thingweb.node-wot#142]
I have the counter.js example and run it with `wot-servient` command. This results in the count property being observable and having `observeproperty` operation for an HTTP form. However, when the longpoll request is done, the counter servient throws the following error but keeps working, i.e. does not crash the servient:
```
HttpServer on port 8080 received 'GET /counter/properties/count/observable' from [::ffff:10.181.212.103]:57820
HttpServer on port 8080 replied with '200' to [::ffff:10.181.212.103]:57820
HttpServer on port 8080 closed Event connection
(node:1155786) UnhandledPromiseRejectionWarning: Error: ExposedThing 'counter', no event found for 'count'
    at /home/eko/git/thingweb.node-wot/packages/core/dist/exposed-thing.js:295:24
    at new Promise (<anonymous>)
    at Object.ExposedThing.unsubscribeEvent (/home/eko/git/thingweb.node-wot/packages/core/dist/exposed-thing.js:289:16)
    at ServerResponse.<anonymous> (/home/eko/git/thingweb.node-wot/packages/binding-http/dist/http-server.js:411:49)
    at ServerResponse.emit (events.js:215:7)
    at onFinish (_http_outgoing.js:686:10)
    at afterWrite (_stream_writable.js:501:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
(node:1155786) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1155786) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

As can be seen from the error codes, if done in a browser, we get an empty but loaded page.

**Comment by danielpeintner** [comment]
@egekorkan can you confirm that https://github.com/eclipse/thingweb.node-wot/commit/7f361c47032f65d04b485d914ce9d5ed32de0514 resolves the issue...

**Comment by egekorkan** [comment]
I can confirm that this is resolved now
