### ISSUE TITLE
[binding-http] readXproperties still use the old API

### ISSUE THREAD

**Issue by egekorkan** [eclipse/thingweb.node-wot#145]
After doing a GET request to a form with `readallproperties` the following error shows:
```
HttpServer on port 8080 received 'GET /counter/all/properties' from [2001:4ca0:0:f237:e387:a2e0:f191:cc7a]:57172
/home/eko/git/thingweb.node-wot/packages/binding-http/dist/http-server.js:356
                                    var property = thing_1.properties[key].read();
                                                                           ^

TypeError: thing_1.properties[key].read is not a function
    at HttpServer.handleRequest (/home/eko/git/thingweb.node-wot/packages/binding-http/dist/http-server.js:356:76)
    at Server.<anonymous> (/home/eko/git/thingweb.node-wot/packages/binding-http/dist/http-server.js:44:73)
    at Server.emit (events.js:210:5)
    at parserOnIncoming (_http_server.js:745:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
```
In the GitHub, it can be see [here](https://github.com/eclipse/thingweb.node-wot/blob/master/packages/binding-http/src/http-server.ts#L457). 

To reproduce, run the counter.js example and do a GET request to `localhost:8080/counter/all/properties`

**Comment by danielpeintner** [comment]
The commit should fix the error. If not please reopen.

**Comment by egekorkan** [comment]
It is indeed fixed, thank you!
