### ISSUE TITLE
Http server decode URI error crashes servient.

### ISSUE THREAD

**Issue by relu91** [eclipse/thingweb.node-wot#389]
Unfortunately, I cannot give more context than what the title already says. Here is the error that caused a crash in my application:

```
/usr/local/lib/node_modules/@node-wot/cli/node_modules/@node-wot/binding-http/dist/http-server.js:337
        var segments = decodeURI(requestUri.pathname).split("/");
                       ^

URIError: URI malformed
    at decodeURI (<anonymous>)
    at HttpServer.handleRequest (/usr/local/lib/node_modules/@node-wot/cli/node_modules/@node-wot/binding-http/dist/http-server.js:337:24)     
    at Server.<anonymous> (/usr/local/lib/node_modules/@node-wot/cli/node_modules/@node-wot/binding-http/dist/http-server.js:44:73)
    at Server.emit (events.js:198:13)
    at parserOnIncoming (_http_server.js:695:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:17)
```

node-wot version: 0.7.1

**Comment by danielpeintner** [comment]
Since `decodeURI` is a library function I do not know better than catching any error...
