### ISSUE TITLE
Test fails sporadically on GitHub

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#434]
~~see https://github.com/eclipse/thingweb.node-wot/runs/2969887900~~
EDIT: I re-run the tests and it worked after 2 re-tries..

But I can see similar issues elsewhere: https://github.com/eclipse/thingweb.node-wot/runs/2618112114

### MQTT

```
lerna ERR! npm run test stderr:
[core/servient] Servient generating ID for 'TestWoTMQTT': 'urn:uuid:5501dc2a-134b-45a7-bba8-cab28ec9ca62'
(node:1624) UnhandledPromiseRejectionWarning: AssertionError: expected true to equal false
    at D:\a\thingweb.node-wot\thingweb.node-wot\packages\binding-mqtt\test\mqtt-client-subscribe-test.ts:79:57
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1624) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1624) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @node-wot/binding-mqtt@0.7.7 test: `mocha --compilers ts:ts-node/register`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @node-wot/binding-mqtt@0.7.7 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

### CoAP

```
  1) CoAP client implementation should apply form information:
     Error: bind EACCES 0.0.0.0:56833
      at dgram.js:357:20
      at processTicksAndRejections (internal/process/task_queues.js:83:21)

  2) CoAP client implementation should re-use port:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)

  3) CoAP server implementation should start and stop a server:
     Error: bind EACCES 0.0.0.0:56831
      at dgram.js:357:20
      at processTicksAndRejections (internal/process/task_queues.js:83:21)


lerna ERR! npm run test stderr:
(node:1080) UnhandledPromiseRejectionWarning: Error: bind EACCES 0.0.0.0:56834
    at dgram.js:357:20
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
```

Locally I *never* had issues in the recent past..

**Comment by egekorkan** [comment]
Just to be sure, you mean that the exact code passes tests locally but not on GitHub?

**Comment by danielpeintner** [comment]
Yes, it works locally.

Moreover, it fails on certain runs on GitHub only (we do have 12 runs based on OS and node.js version).

**Comment by danielpeintner** [comment]
It happened again, see https://github.com/eclipse/thingweb.node-wot/runs/2988294625?check_suite_focus=true

The PR used to work before, see https://github.com/eclipse/thingweb.node-wot/pull/435

**Comment by danielpeintner** [comment]
It still fails, now for mqtts testcase.
see https://github.com/eclipse/thingweb.node-wot/runs/3282367458

For now lets skip this test till we have a solution to not cluster PRs with failures that are not relevant.
see https://github.com/eclipse/thingweb.node-wot/pull/468
**_TODO_** fix skipped test for GitHub

**Comment by danielpeintner** [comment]
It seems we have *stable* tests at the moment. Hence I close the issue.
