### ISSUE TITLE
Is it possible to connect to a secured mosquitto broker using a certificate?

### ISSUE THREAD

**Issue by alvarogar23** [eclipse/thingweb.node-wot#455]
Hi, I have set up a mosquitto broker with tls so in order to connect to it, the client must have the certificate. Is there any way to use the certificate by client when connecting to the broker so the connection is succesful?.

When I try to connect to the broker it doesn´t allow the connection because the client has no certificate.
```
[binding-mqtt] MqttBrokerServer trying to connect to secured broker at mqtt://localhost:8883
[binding-mqtt] MqttBrokerServer could not connect to broker at mqtt://localhost:8883
(node:16188) UnhandledPromiseRejectionWarning: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
(node:16188) Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
(node:16188) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
[binding-mqtt] MqttBrokerServer could not connect to broker at mqtt://localhost:8883
[binding-mqtt] MqttBrokerServer could not connect to broker at mqtt://localhost:8883
[binding-mqtt] MqttBrokerServer could not connect to broker at mqtt://localhost:8883
```

This is my mosquitto.conf file
[mosquitto_conf.txt](https://github.com/eclipse/thingweb.node-wot/files/6911635/mosquitto_conf.txt)

**Comment by egekorkan** [comment]
So it is not supported in node-wot. I have looked into the mqtt library we use and there it is also not super clear if it is supported (https://github.com/mqttjs/MQTT.js#mqttclientstreambuilder-options). It talks about authentification and certificates in some versions. Could you test a raw MQTT.js script with your browser to see how it works?

**Comment by alvarogar23** [comment]
So what I have done has solved my problem for my Server Servient but not for my Client Servient. I have created a MQTT mosca broker and it uses the certificates, then I connect the Server Servient to the broker and MQTT over TLS works perfectly, I have checked it in Wireshark as the following image shows.

![image](https://user-images.githubusercontent.com/55927038/127916469-ad2ac412-8fc3-4fb8-a382-bb1000d531c4.png)

The problem comes in the Client Servient, it gives me the following error

```
[core/helpers] Helpers found scheme 'mqtts'
[core/consumed-thing] ConsumedThing 'AireAcondicionado' has no client in cache (-1)
[core/servient] Servient checking for 'mqtts' scheme in 1 ClientFactories
Suscrito
(node:17036) UnhandledPromiseRejectionWarning: Error: ConsumedThing 'AireAcondicionado' missing ClientFactory for 'mqtts'
    at Object.ConsumedThing.getClientFor (C:\Users\alvar\Desktop\Servient-main-copia\node_modules\@node-wot\core\dist\consumed-thing.js:154:27)   
    at C:\Users\alvar\Desktop\Servient-main-copia\node_modules\@node-wot\core\dist\consumed-thing.js:392:32
    at new Promise (<anonymous>)
    at Object.ConsumedThing.subscribeEvent (C:\Users\alvar\Desktop\Servient-main-copia\node_modules\@node-wot\core\dist\consumed-thing.js:386:16) 
    at C:\Users\alvar\Desktop\Servient-main-copia\mando.js:65:23
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17036) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17036) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I don´t know why mqtts does work for the server but not for the client.

This is the code that gives the error.

```
var Servient = require("@node-wot/core").Servient;
var MqttClientFactory = require("@node-wot/binding-mqtt").MqttClientFactory;
var pairing = require('./pairing.js');
var controllerID = 5;
const express = require('express');
const app = express();


Helpers = require("@node-wot/core").Helpers;

//Creamos el Servient y el protocolo MQTT

let servient = new Servient();
servient.addClientFactory(new MqttClientFactory(null));

//Thing description

let td = `{
    "@context": "https://www.w3.org/2019/wot/td/v1",
    "title": "AireAcondicionado",
    "id": "urn:dev:wot:mqtts:AireAcondicionado",
    "actions" : {
        "OnOff": {
            "forms": [
                {"href": "mqtts://localhost:8443/AireAcondicionado/actions/OnOff"}
            ]
        },
        "incrementar": {
            "forms": [
                {"href": "mqtts://localhost:8443/AireAcondicionado/actions/incrementar"}
            ]
        },
        "decrementar": {
            "forms": [
                {"href": "mqtts://localhost:8443/AireAcondicionado/actions/decrementar"}
            ]
        },
        "leerTemperatura": {
            "forms": [
                {"href": "mqtts://localhost:8443/AireAcondicionado/actions/leerTemperatura"}
            ]
        }
    }, 
    "events": {
        "estadoTemperatura": {
            "type": "integer",
            "forms": [
                {"href": "mqtts://localhost:8443/AireAcondicionado/events/estadoTemperatura"}
            ]
        } 
    } 
}`;

var license = pairing.createLicense(controllerID)

if(pairing.verify(license) == true){
    console.log('Emparejamiento correcto');
    try {
        servient.start().then((WoT) => {
            WoT.consume(JSON.parse(td)).then((thing) => {
                console.info(td);
    
                
    
                thing.subscribeEvent(
                    "estadoTemperatura",
                    (temperatura) => console.info("value:", temperatura),
                    (e) => console.error("Error: %s", e),
                    () => console.info("Completado")
                )
    
                console.info("Suscrito");
    
                app.set('view engine', 'jade');
    
                app.get("/mando", function (req, res) {
                    res.render("mando", {
                        title: "Mando del aire"
                    });
                });
    
                app.get("/subirTemperatura", function (req, res) {
                    
                        res.render("mando", {
                            title: "Mando del aire",
                            subirTemperatura: thing.invokeAction('incrementar')
                        });
                    
                    
                    
                });
    
                app.get("/bajarTemperatura", function (req, res) {
                    
                        res.render("mando", {
                            title: "Mando del aire",
                            subirTemperatura: thing.invokeAction('decrementar')
                        });
                    
                });
    
                app.get("/mostrarTemperatura", function (req, res) {
                    res.render("mando");
                });
    
                app.listen(4000);
            });
        });
    } catch (err) {
        console.error("Error en el script: ", err);
    }

}else{

    pairing.errorDifferentId();

}



```

@egekorkan I'll try to do that raw test.

**Comment by relu91** [comment]
```

[core/helpers] Helpers found scheme 'mqtts'

[core/consumed-thing] ConsumedThing 'AireAcondicionado' has no client in cache (-1)

[core/servient] Servient checking for 'mqtts' scheme in 1 ClientFactories

Suscrito

(node:17036) UnhandledPromiseRejectionWarning: Error: ConsumedThing 'AireAcondicionado' missing ClientFactory for 'mqtts'

at Object.ConsumedThing.getClientFor (C:\Users\alvar\Desktop\Servient-main-copia\node_modules\@node-wot\core\dist\consumed-thing.js:154:27)

at C:\Users\alvar\Desktop\Servient-main-copia\node_modules\@node-wot\core\dist\consumed-thing.js:392:32

at new Promise (<anonymous>)

at Object.ConsumedThing.subscribeEvent (C:\Users\alvar\Desktop\Servient-main-copia\node_modules\@node-wot\core\dist\consumed-thing.js:386:16)

at C:\Users\alvar\Desktop\Servient-main-copia\mando.js:65:23

at processTicksAndRejections (internal/process/task_queues.js:95:5)

(Use `node --trace-warnings ...` to show where the warning was created)

(node:17036) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

(node:17036) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

This happens because `node-wot` uses the URL scheme to match the right client. Sadly the mqtt binding only register a client for `mqtt` scheme but not for `mqtts`. I think I can fix it with a small PR. Let me try 👍🏻

**Comment by relu91** [comment]
Done, when the PR lands you should be able to connect to your broker: 
```js
var Servient = require("@node-wot/core").Servient;
var MqttClientFactory = require("@node-wot/binding-mqtt").MqttsClientFactory;
var pairing = require('./pairing.js');
var controllerID = 5;
const express = require('express');
const app = express();


Helpers = require("@node-wot/core").Helpers;


let servient = new Servient();
// note the usage of Mqtts not Mqtt. 
// anathor point I am using rejectUnauthorized but in production you should provide your certificate to be protected
// against men in the middle attacts
servient.addClientFactory(new MqttsClientFactory({rejectUnauthorized: false}));
```

**Comment by alvarogar23** [comment]
So I have been testing MqttsClientFactory and at least for me it throws the error that MqttsClientFactory is not a constructor

```
servient.addClientFactory(new MqttsClientFactory({rejectUnauthorized: false}));
                          ^

TypeError: MqttsClientFactory is not a constructor
    at Object.<anonymous> (C:\Users\alvar\Desktop\MQTTS-Final\mando.js:11:27)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

It is weird because if I ctrl+click the MqttsClientFactory constructor it redirects me to the mqtts-client-factory.d file.

I´ll try to find the solution.

**Comment by alvarogar23** [comment]
There is a constructor problem with MqttsClientFacory. I have found the solution but other problems have appeared, everything is in  **Connect to mqtts** #456
