### ISSUE TITLE
When I invoke an action it returns undefined

### ISSUE THREAD

**Issue by alvarogar23** [eclipse/thingweb.node-wot#496]
Hi, in my project I have defined the following action handler that is used to pair two devices:

**Server servient.**
```
let allowedID = [1, 2];

thing.setActionHandler('pairing', (id) => {
            return allowedID.includes(id)
            
        });
```

Then in my client Servient I invoke the action in the following way and it returns undefined when it should be returning true or false:

**Client Servient.**
```
thing.invokeAction('pairing', 1).then(x => console.log(x));
```

I don't know if my code is wrong or if it is another error.

Thanks in advance

**Comment by danielpeintner** [comment]
Questions:
* do you get an error? The issue does not say anything?
* I think you are missing `async` OR return `Promise`?
```
   thing.setActionHandler('pairing', async (id) => {
            return allowedID.includes(id)
        });

```

**Comment by alvarogar23** [comment]
So i previously tried putting async and I have tried it again, the program works perfectly but the value I need still being undefined. This is a part of the messages I get:

```
[core/helpers] Helpers found scheme 'mqtts'
[core/consumed-thing] ConsumedThing 'AireAcondicionado' has no client in cache (-1)
[core/servient] Servient checking for 'mqtts' scheme in 1 ClientFactories
[core/servient] Servient creating client for scheme 'mqtts'
[core/consumed-thing] ConsumedThing 'AireAcondicionado' got new client for 'mqtts'
[core/consumed-thing] ConsumedThing 'AireAcondicionado' invoking mqtts://localhost:8443/AireAcondicionado/actions/emparejamiento with '1'        
[core/content-serdes] ContentSerdes serializing to application/json
[core/helpers] Helpers found scheme 'mqtts'
[core/consumed-thing] ConsumedThing 'AireAcondicionado' chose cached client for 'mqtts'
[core/consumed-thing] ConsumedThing 'AireAcondicionado' subscribing to mqtts://localhost:8443/AireAcondicionado/events/estadoTemperatura
Suscrito
[core/content-serdes] ContentSerdes deserializing from application/json
Pairing value: undefined
[binding-mqtt] Received MQTT message (topic, data): (/AireAcondicionado/events/estadoTemperatura, 10)
[core/content-serdes] ContentSerdes deserializing from application/json
value: 10
[binding-mqtt] Received MQTT message (topic, data): (/AireAcondicionado/events/estadoTemperatura, 10)
[core/content-serdes] ContentSerdes deserializing from application/json
value: 10
```

As you can see, in the line where Pairing value is, it returns undefined even when making the actionhandler async.

**Comment by danielpeintner** [comment]
@alvarogar23 may I ask you to provide a [SSCCE](http://sscce.org/) for the use-case (client/server?)

I also suggest you to use an other binding like HTTP. Does this work?

**Comment by alvarogar23** [comment]
So this is the example of my code:

**Server Servient.**

```
var Servient = require('@node-wot/core').Servient;
var MqttBrokerServer = require('@node-wot/binding-mqtt').MqttBrokerServer;

//Creamos el servient y el protocolo MQTT
let brokerUri = 'mqtt://localhost:1883';

let servient = new Servient();
let brokerServer = new MqttBrokerServer(brokerUri, undefined, undefined, undefined, undefined, false);
servient.addServer(brokerServer);

servient.start().then((WoT) => {


    WoT.produce({
        title: 'AireAcondicionado',
        description: 'Aparato de aire acondicionado que muestra la temperatura',
        '@context': [
            'https://www.w3.org/2019/wot/td/v1',
        ],
        properties: {
            allowedID: {
                type: 'array',
                observable: true,
                description: 'Allowed IDs'
            }
        },
        actions: {
            pairing: {
                description: 'Used for pairing devices'
            }
        }


    }).then((thing) => {
        console.log('Producido ' + thing.getThingDescription().title);

        let allowedIDs = [1, 2];

        thing.setPropertyReadHandler('allowedID', async () => allowedIDs);

        thing.setActionHandler('pairing', async (id) => {
            return idPermitida.includes(id);


        });

        thing.expose().then(() => {
            console.info(thing.getThingDescription().title + 'ready');



        });


    }).catch((e) => {
        console.log(e);
    });

});
```

**Client Servient.**

```
var Servient = require("@node-wot/core").Servient;
var MqttClientFactory = require("@node-wot/binding-mqtt").MqttClientFactory

Helpers = require("@node-wot/core").Helpers;

//Creamos el Servient y el protocolo MQTT

let servient = new Servient();
servient.addClientFactory(new MqttClientFactory(/*{rejectUnauthorized: false}*/));

//Thing description

let td = `{
    "@context": "https://www.w3.org/2019/wot/td/v1",
    "title": "AireAcondicionado",
    "id": "urn:dev:wot:mqtt:AireAcondicionado",
    "properties": {
        "allowedID": {
            "type": "integer",
            "forms": [{
                "href": "mqtt://localhost:1883/AireAcondicionado/properties/allowedID"
            }]
        }
    },
    "actions" : {
        "pairing": {
            "forms": [
                {"href": "mqtt://localhost:1883/AireAcondicionado/actions/pairing"}
            ]
        }
    }
}`;

try {

    servient.start().then((WoT) => {
        WoT.consume(JSON.parse(td)).then((thing) => {
            console.info(td);

            thing.invokeAction('pairing', 1).then(x => console.log('Pairing value: '+x));

        });
    });

} catch (err) {
    console.error("Error en el script: ", err);
}
```

**Broker.**

```
var mosca = require('mosca')
var fs = require('fs');



  
const settings = {
  port: 1883
};
  

var server = new mosca.Server(settings);
server.on('ready', setup);

server.on('clientConnected', (client) => {
  console.log('client connected: ' + client.id)
});

server.on('published', (packet) => {
  console.log( 'published : ' + JSON.stringify(packet));
});

// fired when the mqtt server is ready
function setup() {
  console.log('Mosca server is up and running')
}
```

I will also try with the HTTP binding, if I get anything I'll post it here.
Thanks.

**Comment by danielpeintner** [comment]
Did not have the time to try it out but can it be its a scoping issue? Can you try to move the following line _outside_ 

`let allowedIDs = [1, 2];`

... meaning before 

`servient.start().then((WoT) => {`

**Comment by alvarogar23** [comment]
So I have tried putting allowedIDs outside and it keeps returning undefined, and with HTTP it gives me and error when invoking the action.

**HTTP Server Servient.**

```
var Servient = require('@node-wot/core').Servient;
var HttpServer = require('@node-wot/binding-http').HttpServer;


Helpers = require('@node-wot/core');


let servient = new Servient();
servient.addServer(new HttpServer({
    port: 8080 // (default 8080)
}));

let allowedIDs = [1, 2];

servient.start().then((WoT) => {


    WoT.produce({
        title: 'AireAcondicionado',
        description: 'Aparato de aire acondicionado que muestra la temperatura',
        '@context': [
            'https://www.w3.org/2019/wot/td/v1',
        ],
        properties: {
            allowedID: {
                type: 'number',
                description: 'Allowed IDs'
            }
        },
        actions: {
            pairing: {
                description: 'Used for pairing devices'
            }
        }


    }).then((thing) => {
        console.log('Producido ' + thing.getThingDescription().title);

        

        thing.setPropertyReadHandler('allowedID', async () => allowedIDs);

        thing.setActionHandler('pairing', async (id) => {
            return idPermitida.includes(id);


        });

        thing.expose().then(() => {
            console.info(thing.getThingDescription().title + 'ready');



        });


    }).catch((e) => {
        console.log(e);
    });

});
```

**HTTP Client Servient.**

```
var Servient = require("@node-wot/core").Servient;
var HttpClientFactory = require("@node-wot/binding-http").HttpClientFactory;

Helpers = require("@node-wot/core").Helpers;

//Creamos el Servient y el protocolo MQTT

let servient = new Servient();
servient.addClientFactory(new HttpClientFactory(null));

//Thing description

let td = `{
    "@context": "https://www.w3.org/2019/wot/td/v1",
    "title": "AireAcondicionado",
    "id": "urn:dev:wot:mqtt:AireAcondicionado",
    "properties": {
        "allowedID": {
            "type": "integer",
            "forms": [{
                "href": "http://192.168.1.14:8080/AireAcondicionado/properties/allowedID"
            }]
        }
    },
    "actions" : {
        "pairing": {
            "forms": [
                {"href": "http://192.168.1.14:8080/AireAcondicionado/actions/pairing"}
            ]
        }
    }
}`;

let wotHelper = new Helpers(servient);
wotHelper.fetch("http://192.168.1.14:8080/aireacondicionado/").then(async (td) => {
    // using await for serial execution (note 'async' in then() of fetch())
    try {
        servient.start().then((WoT) => {
            WoT.consume(td).then((thing) => {
                thing.invokeAction('pairing').then(x => console.log('Pairing value: '+x));
                
            });
        });
    } catch (err) {
        console.error("Script error:", err);
    }
}).catch((err) => { console.error("Fetch error:", err); });


```

**Error.**

```
[core/wot-impl] WoTImpl consuming TD 'urn:uuid:93aa5d7f-d7a6-447c-87eb-3238ae60ccd9' to instantiate ConsumedThing 'AireAcondicionado'
[core/helpers] Helpers found scheme 'http'
[core/consumed-thing] ConsumedThing 'AireAcondicionado' has no client in cache (-1)
[core/servient] Servient checking for 'http' scheme in 1 ClientFactories
[core/servient] Servient creating client for scheme 'http'
[binding-http] HttpClientFactory creating client for 'http'
[core/consumed-thing] ConsumedThing 'AireAcondicionado' got new client for 'http'
[core/consumed-thing] ConsumedThing 'AireAcondicionado' setting credentials for [HttpClient]
[core/servient] Servient looking up credentials for 'urn:uuid:93aa5d7f-d7a6-447c-87eb-3238ae60ccd9' (@deprecated)
[binding-http] HttpClient using security scheme 'nosec'
[core/consumed-thing] ConsumedThing 'AireAcondicionado' invoking http://192.168.1.14:8080/aireacondicionado/actions/pairing
[binding-http] HttpClient (invokeResource) sending POST  to http://192.168.1.14:8080/aireacondicionado/actions/pairing
[binding-http] HttpClient received 500 from http://192.168.1.14:8080/aireacondicionado/actions/pairing
[binding-http] HttpClient received Content-Type: null
(node:456) UnhandledPromiseRejectionWarning: Error: Server error: Internal Server Error
    at HttpClient.checkFetchResponse (C:\Users\alvar\Desktop\MQTTS-FINAL-2\node_modules\@node-wot\binding-http\dist\http-client.js:338:19)       
    at HttpClient.<anonymous> (C:\Users\alvar\Desktop\MQTTS-FINAL-2\node_modules\@node-wot\binding-http\dist\http-client.js:155:30)
    at step (C:\Users\alvar\Desktop\MQTTS-FINAL-2\node_modules\@node-wot\binding-http\dist\http-client.js:33:23)
    at Object.next (C:\Users\alvar\Desktop\MQTTS-FINAL-2\node_modules\@node-wot\binding-http\dist\http-client.js:14:53)
    at fulfilled (C:\Users\alvar\Desktop\MQTTS-FINAL-2\node_modules\@node-wot\binding-http\dist\http-client.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:456) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:456) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by danielpeintner** [comment]
There are several minor issues in your code

Server:
* mixing variable allowedIDs  vs. idPermitida
* no checking whether input in action is given .. id is always undefined in your sample since it is not given

Client:
* calls invokeAction without id argument

attached the modified samples..

Note: what I noticed is that return `false` somehow gets also interpreted as `undefined` ... safer to use `Boolean(...)`

Server

```JS
var Servient = require('@node-wot/core').Servient;
var HttpServer = require('@node-wot/binding-http').HttpServer;

Helpers = require('@node-wot/core');

let servient = new Servient();
servient.addServer(new HttpServer({
    port: 8080 // (default 8080)
}));

let allowedIDs = [1, 2];

servient.start().then((WoT) => {
    WoT.produce({
        title: 'AireAcondicionado',
        description: 'Aparato de aire acondicionado que muestra la temperatura',
        '@context': [
            'https://www.w3.org/2019/wot/td/v1',
        ],
        properties: {
            allowedID: {
                type: 'number',
                description: 'Allowed IDs'
            }
        },
        actions: {
            pairing: {
                description: 'Used for pairing devices',
		output: {
			type: 'boolean'
		}
            }
        }
    }).then((thing) => {
        console.log('Producido ' + thing.getThingDescription().title);
		
        thing.setPropertyReadHandler('allowedID', async () => allowedIDs);
		
        thing.setActionHandler('pairing', async (id) => {
            let res = false;
            if (id) {
                console.log("id: " + id );
                console.log("allowedIDsA: " + JSON.stringify(allowedIDs));
                res = allowedIDs.includes(id);
                console.log("allowedIDsB: " + JSON.stringify(res));
            } else {
                console.error("no id given");
            }
            console.error("res: " + res);
            return res;
        });

	thing.expose().then(() => {
            console.info(thing.getThingDescription().title + 'ready');
        });
    }).catch((e) => {
        console.log(e);
    });
});
```

Client

```JS
var Servient = require("@node-wot/core").Servient;
var HttpClientFactory = require("@node-wot/binding-http").HttpClientFactory;

Helpers = require("@node-wot/core").Helpers;

//Creamos el Servient y el protocolo MQTT

let servient = new Servient();
servient.addClientFactory(new HttpClientFactory(null));

//Thing description

let td = `{
    "@context": "https://www.w3.org/2019/wot/td/v1",
    "title": "AireAcondicionado",
    "id": "urn:dev:wot:mqtt:AireAcondicionado",
    "properties": {
        "allowedID": {
            "type": "integer",
            "forms": [{
                "href": "http://localhost:8080/AireAcondicionado/properties/allowedID"
            }]
        }
    },
    "actions" : {
        "pairing": {
            "forms": [
                {"href": "http://localhost:8080/AireAcondicionado/actions/pairing"}
            ]
        }
    }
}`;

let wotHelper = new Helpers(servient);
wotHelper.fetch("http://localhost:8080/aireacondicionado/").then(async (td) => {
    // using await for serial execution (note 'async' in then() of fetch())
    try {
        servient.start().then((WoT) => {
            WoT.consume(td).then(async (thing) => {
                let y = await thing.readProperty('allowedID');
                console.log('y: '+ y)

		let x1 = await thing.invokeAction('pairing', 1);
		console.log('Pairing value 1: '+ x1)

                let x5 = Boolean(await thing.invokeAction('pairing', 5));
		console.log('Pairing value 5: '+ x5)

                // no input, error
                let x = Boolean(await thing.invokeAction('pairing'));
		console.log('Pairing no value: '+ x)
            });
        });
    } catch (err) {
        console.error("Script error:", err);
    }
}).catch((err) => { console.error("Fetch error:", err); });
```

**Comment by alvarogar23** [comment]
So yes, for HTTP it works properly but I have adapted it for MQTT and it might be related with the protocol becasue it keeps returnning undefined:

**Server Servient**

```
var Servient = require('@node-wot/core').Servient;
var MqttBrokerServer = require('@node-wot/binding-mqtt').MqttBrokerServer;

//Creamos el servient y el protocolo MQTT
let brokerUri = 'mqtt://localhost:1883';

let servient = new Servient();
let brokerServer = new MqttBrokerServer(brokerUri, undefined, undefined, undefined, undefined, false);
servient.addServer(brokerServer);

let allowedIDs = [1, 2];

servient.start().then((WoT) => {



    WoT.produce({
        title: 'AireAcondicionado',
        description: 'Aparato de aire acondicionado que muestra la temperatura',
        '@context': [
            'https://www.w3.org/2019/wot/td/v1',
        ],
        properties: {
            
            allowedID: {
                type: 'number',
                description: 'Allowed IDs'
            }
        },
        actions: {
            pairing: {
                description: 'Apaga o enciende el aire',
                output: {
                    type: 'boolean'
                }
            }
        },
        



    }).then((thing) => {
        console.log('Producido ' + thing.getThingDescription().title);



        thing.setPropertyReadHandler('allowedID', async () => allowedIDs);

        

        thing.setActionHandler('pairing', async (id) => {
            let res = false;
            if (id) {
                console.log("id: " + id );
                console.log("allowedIDsA: " + JSON.stringify(allowedIDs));
                res = allowedIDs.includes(id);
                console.log("allowedIDsB: " + JSON.stringify(res));
            } else {
                console.error("no id given");
            }
            console.error("res: " + res);
            return res;
        });

        

        thing.expose().then(() => {
            console.info(thing.getThingDescription().title + 'ready');

            

        });


        


    }).catch((e) => {
        console.log(e);
    });

});


```

**Client Servient**

```
var Servient = require("@node-wot/core").Servient;
var MqttClientFactory = require("@node-wot/binding-mqtt").MqttClientFactory
const controllerID = 5;



Helpers = require("@node-wot/core").Helpers;

//Creamos el Servient y el protocolo MQTT

let servient = new Servient();
servient.addClientFactory(new MqttClientFactory());

//Thing description

let td = `{
    "@context": "https://www.w3.org/2019/wot/td/v1",
    "title": "AireAcondicionado",
    "id": "urn:dev:wot:mqtt:AireAcondicionado",
    "properties": {
        "allowedID": {
            "type": "number",
            "forms": [{
                "href": "mqtt://localhost:1883/AireAcondicionado/properties/allowedID"
            }]
        }
    },
    "actions" : {
        "pairing": {
            "forms": [
                {"href": "mqtt://localhost:1883/AireAcondicionado/actions/pairing"}
            ]
        } 
    }
}`;

try {

    servient.start().then((WoT) => {
        WoT.consume(JSON.parse(td)).then((thing) => {
            console.info(td);

            thing.invokeAction('pairing', controllerID).then(x => console.log('Pairing value: '+x));

            

            console.info("Suscrito");

            
        });
    });

} catch (err) {
    console.error("Error en el script: ", err);
}
```

**Broker**

```
var mosca = require('mosca')

  
const settings = {
  port: 1883
};
  

var server = new mosca.Server(settings);
server.on('ready', setup);

server.on('clientConnected', (client) => {
  console.log('client connected: ' + client.id)
});

server.on('published', (packet) => {
  console.log( 'published : ' + JSON.stringify(packet));
});

// fired when the mqtt server is ready
function setup() {
  console.log('Mosca server is up and running')
}
```

I have been figuring out if I have an error but I dont´t see anaything so maybe it can be the protocol.

**Comment by alvarogar23** [comment]
So I have found the problem , and it is that read and write are not implemented in mqtt binding:

```
this.readResource = function (form) {
            return new Promise(function (resolve, reject) {
                throw new Error('Method not implemented.');
            });
        };
        this.writeResource = function (form, content) {
            return new Promise(function (resolve, reject) {
                throw new Error('Method not implemented.');
            });
        };
```

**Comment by danielpeintner** [comment]
Yes, MQTT is rather limited at the moment
https://github.com/eclipse/thingweb.node-wot/blob/master/packages/binding-mqtt/src/mqtt-client.ts.

see also https://github.com/eclipse/thingweb.node-wot/issues/457

**Comment by alvarogar23** [comment]
So I guess there is no way to pass variables between clients with MQTT protocol. Am I right?

**Comment by egekorkan** [comment]
You can do that as well, just not with properties. You can write a custom action that is used for setting variables.

**Comment by alvarogar23** [comment]
Yes, I can do for example the following action in the Server servient:

```
thing.setActionHandler('pairing', async (id) => {
            
            let allowedIDs = [1, 2];
            let res = false;

            if(allowedIDs.includes(id) == true){
                res = true;
            }

            return res;
        })
```

But the problem comes in the client Servient, when I invoke the action it returns undefined even if I return a variable and not a property.

```
thing.invokeAction('pairing', controllerID).then(x => console.log(x));
```

Pairing value return Undefined:

```
[core/helpers] Helpers found scheme 'mqtts'
[core/consumed-thing] ConsumedThing 'AireAcondicionado' has no client in cache (-1)
[core/servient] Servient checking for 'mqtts' scheme in 1 ClientFactories
[core/servient] Servient creating client for scheme 'mqtts'
[core/consumed-thing] ConsumedThing 'AireAcondicionado' got new client for 'mqtts'
[core/consumed-thing] ConsumedThing 'AireAcondicionado' invoking mqtts://localhost:8443/AireAcondicionado/actions/pairing with '5'
[core/content-serdes] ContentSerdes serializing to application/json
[core/helpers] Helpers found scheme 'mqtts'
[core/consumed-thing] ConsumedThing 'AireAcondicionado' chose cached client for 'mqtts'
[core/consumed-thing] ConsumedThing 'AireAcondicionado' subscribing to mqtts://localhost:8443/AireAcondicionado/events/estadoTemperatura
Suscrito
[core/content-serdes] ContentSerdes deserializing from application/json
Pairing value: undefined
[binding-mqtt] Received MQTT message (topic, data): (/AireAcondicionado/events/estadoTemperatura, 10)
[core/content-serdes] ContentSerdes deserializing from application/json
value: 10
[binding-mqtt] Received MQTT message (topic, data): (/AireAcondicionado/events/estadoTemperatura, 10)
[core/content-serdes] ContentSerdes deserializing from application/json
value: 10
```

I don´t know if I am not understanding what you are saying.
Thanks.

**Comment by danielpeintner** [comment]
I am not 100% sure who worked on MQTT but it seems to report *nothing*

https://github.com/eclipse/thingweb.node-wot/blob/6b5b03bd86954d51c1592b058f6820b992f4d8ef/packages/binding-mqtt/src/mqtt-client.ts#L108-L109

**Comment by alvarogar23** [comment]
I will try to find a solution, thanks.

**Comment by danielpeintner** [comment]
Note: need to calrify "who" is responsible, see https://github.com/eclipse/thingweb.node-wot/issues/508

**Comment by relu91** [comment]
> I am not 100% sure who worked on MQTT but it seems to report _nothing_
> 
> https://github.com/eclipse/thingweb.node-wot/blob/6b5b03bd86954d51c1592b058f6820b992f4d8ef/packages/binding-mqtt/src/mqtt-client.ts#L108-L109

yes this is something that I found weird when I was working on binding implementation a while ago. After thinking about it I ended up considering the fact that MQTT actually does not have responses for `publish` operations. You would need a "small protocol" to achieve something similar to a request-response (define special payloads and an algorithm involving probably multiple publishing and subscribing operations). MQTT 5 has other native protocol message types to achieve a request and response. if we want to support action outputs I think is better to leave it to the protocol. 

I think such considerations should be addressed in the protocol binding spec, as well

**Comment by alvarogar23** [comment]
But then if publish does not have responses, reading a property of a Server Servient from a client Servient is not possible? Because it would return nothing.

**Comment by relu91** [comment]
> But then if publish does not have responses, reading a property of a Server Servient from a client Servient using readProperty function wouldn't be possible because method is not implemented yet?

No this is a possible cause in this case you can subscribe to a topic and receiving back the retained message. Actions are trickier because the outputs depend on the inputs, so you would need a "protocol" to remember who requested the action execution and with which input parameters.
