### ISSUE TITLE
OPCUA logs error

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#729]
when running OPC-UA tests I see logs like

```
Error: Cannot find enumeration with type Variant
    at getEnumeration (C:\Projects\WoT\thingweb\thingweb.node-wot-danielpeintner\node_modules\node-opcua-data-value\node_modules\node-opcua-factory\source\factories_enumerations.ts:94:15)
    at figureOutSchema (C:\Projects\WoT\thingweb\thingweb.node-wot-danielpeintner\node_modules\node-opcua-data-value\node_modules\node-opcua-factory\source\factories_structuredTypeSchema.ts:79:37)
    at buildField (C:\Projects\WoT\thingweb\thingweb.node-wot-danielpeintner\node_modules\node-opcua-data-value\node_modules\node-opcua-factory\source\factories_structuredTypeSchema.ts:97:20)
    at Array.map (<anonymous>)
    at new StructuredTypeSchema (C:\Projects\WoT\thingweb\thingweb.node-wot-danielpeintner\node_modules\node-opcua-data-value\node_modules\node-opcua-factory\source\factories_structuredTypeSchema.ts:162:38)
    at buildStructuredType (C:\Projects\WoT\thingweb\thingweb.node-wot-danielpeintner\node_modules\node-opcua-data-value\node_modules\node-opcua-factory\source\factories_structuredTypeSchema.ts:327:12)
    at Object.<anonymous> (C:\Projects\WoT\thingweb\thingweb.node-wot-danielpeintner\node_modules\node-opcua-data-value\source\datavalue.ts:215:66)
```

@erossignon

**Comment by danielpeintner** [comment]
For the time being I "disabled" testing, see https://github.com/eclipse/thingweb.node-wot/pull/727/commits/cb3761977698bce7d72ee5d0250dbfbf571e54ef

This needs to be undone...

**Comment by erossignon** [comment]
Hi Daniel, I can't reproduce on master... is that something specific to 0.8.1 that is not yet merged ?

**Comment by erossignon** [comment]
Fix on https://github.com/danielpeintner/thingweb.node-wot/pull/2

How to fix ? :

     npm run ncu:opcua -ws
     npm install

**Comment by danielpeintner** [comment]
fixed by https://github.com/eclipse/thingweb.node-wot/pull/727/commits/9746075c208c4d085013cbd714b9cf072bea83b2

**Comment by danielpeintner** [comment]
> npm run ncu:opcua -ws

Updating is fine, but "why" wasn't there any issue with CI tests... shouldn't they report a problem. You changed patch AND minor version..

**Comment by relu91** [comment]
Can we close this?

**Comment by erossignon** [comment]
yes,
