### ISSUE TITLE
CoAP ClientFactory

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#741]
@relu91 @danielpeintner 
I haven't really tested but I was exploring the COAP example in readme and saw there

`servient.addClientFactory(new CoapClientFactory(null));`

How is this legit if it passes null as CoapServer, which was working before but in v8 the field is not nullable anymore?

_Originally posted by @fatadel in https://github.com/eclipse/thingweb.node-wot/issues/721#issuecomment-1103292782_

**Comment by danielpeintner** [comment]
I did test an updated code with passing CoapServer  (attached the sample) and I now see another issue?

@JKRhb do you know "why" getSocket() is not a function?

```
[binding-coap] CoapClientFactory creating client for 'coap'
Fetch error: TypeError: server.getSocket is not a function
    at new CoapClient (C:\Users\mchn4310\node_modules\@node-wot\binding-coap\dist\coap-client.js:41:65)
    at CoapClientFactory.getClient (C:\Users\mchn4310\node_modules\@node-wot\binding-coap\dist\coap-client-factory.js:14:16)
    at Servient.getClientFor (C:\Users\mchn4310\node_modules\@node-wot\core\dist\servient.js:198:53)
    at C:\Users\mchn4310\node_modules\@node-wot\core\dist\helpers.js:112:37
    at new Promise (<anonymous>)
    at Helpers.fetch (C:\Users\mchn4310\node_modules\@node-wot\core\dist\helpers.js:111:16)
```

**Comment by JKRhb** [comment]
Hmm, I tried to reproduce the issue but didn't encounter any problems.

Passing the server like this works fine:

```js
Servient = require("@node-wot/core").Servient;
CoapClientFactory = require("@node-wot/binding-coap").CoapClientFactory;
CoapServer = require("@node-wot/binding-coap").CoapServer;

Helpers = require("@node-wot/core").Helpers;

// create Servient and add CoAP binding
let servient = new Servient();
const server = new CoapServer();
servient.addServer(server);
servient.addClientFactory(new CoapClientFactory(server));

let wotHelper = new Helpers(servient);
wotHelper
    .fetch("coap://plugfest.thingweb.io:5683/testthing")
    .then(async (td) => {
        // using await for serial execution (note 'async' in then() of fetch())
        try {
            const WoT = await servient.start();
            const thing = await WoT.consume(td);

            // read property
            const read1 = await thing.readProperty("string");
            console.log("string value is: ", await read1.value());
        } catch (err) {
            console.error("Script error:", err);
        }
    })
    .catch((err) => {
        console.error("Fetch error:", err);
    });
```

Also, the server argument is in fact nullable at the moment? Or am I missing something?

https://github.com/eclipse/thingweb.node-wot/blob/b25b54cff2a9c3238400cef852c9cf757980e6e8/packages/binding-coap/src/coap-client.ts#L47

**Comment by JKRhb** [comment]
I just found where the non-nullable server argument was introduced: https://github.com/eclipse/thingweb.node-wot/commit/0b2510ac0097500f1206b3df41fc98a09a68f62e

**Comment by JKRhb** [comment]
I think this issue should be fixed by now, right?
